In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:

print("Testing IO for point cloud ...")
sample_pcd_data = o3d.data.PCDPointCloud()
pcd = o3d.io.read_point_cloud("/home/iana/Atlas/Arch.ply")
print(pcd)

o3d.io.write_point_cloud("copy_of_fragment.pcd", pcd)

Testing IO for point cloud ...
[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/fragment.pcd
[Open3D INFO] Downloaded to /home/iana/open3d_data/download/PCDPointCloud/fragment.pcd
PointCloud with 1720 points.


True

In [3]:
print("Load a ply point cloud, print it, and render it")
ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud("/home/iana/Atlas/Arch.ply")
#print(pcd)
#print(np.asarray(pcd.points))
# o3d.visualization.draw_geometries([pcd])



aabb = pcd.get_axis_aligned_bounding_box()
aabb.color = (1, 0, 0)
obb = pcd.get_oriented_bounding_box()
obb.color = (0, 1, 0)
o3d.visualization.draw_geometries([pcd, aabb, obb])
x = np.asarray(obb.get_box_points())
print(x)

Load a ply point cloud, print it, and render it
[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/fragment.ply
[Open3D INFO] Downloaded to /home/iana/open3d_data/download/PLYPointCloud/fragment.ply
[[ 1.07076887  0.49715754  0.83005751]
 [ 1.26622805 -0.80911457  0.73557315]
 [ 0.27439615  0.3752837   0.86754558]
 [ 1.04617629  0.52477215  0.39740343]
 [ 0.44526275 -0.9033738   0.34040714]
 [ 0.24980357  0.40289831  0.4348915 ]
 [ 1.24163547 -0.78149996  0.30291908]
 [ 0.46985533 -0.93098841  0.77306122]]
